apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate-events-relay
  labels:
    app: frigate-events-relay
    platform: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate-events-relay
      platform: frigate
  template:
    metadata:
      labels:
        app: frigate-events-relay
        platform: frigate
    spec:
      containers:
        - name: app
          image: ghcr.io/brilliant-monkey/frigate-kafka-relay
          env:
            - name: FRIGATE_KAFKA_RELAY_CONFIG_PATH
              value: "/app/config.yml"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - mountPath: /app/config.yml
              subPath: secret.yml
              name: secret
      volumes:
        - name: secret
          secret:
            secretName: frigate-events-relay
            
