name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: tag
      with:
        script: |
          core.exportVariable('IMAGE_TAG', context.sha.substring(0,7))
    - uses: actions/checkout@v3
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.3.0
      with:
        images: ghcr.io/${{ github.repository }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        push: true
        tags: ${{ IMAGE_TAG }}
