name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/github-script@v6
      id: tag
      with:
        result-encoding: string
        script: return context.sha.substring(0,7)
    - name: login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: create image from repository
      run: docker build -t ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.result }} .
    - name: push image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.result }}
