name: pull-request

on:
  pull_request:
    branches:
      - "*"

env:
  SHA: github.sha
  REPO: github.repository
  PR: github.event.pull_request.number

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: tag
      run: |
        export TAG="$(echo $SHA | cut -c 1-6)"
        echo "::set-output name=image_name::$(echo ghcr.io/"$REPO":"$TAG-$PR")"
    outputs:
      image_name: "${{ steps.tag.outputs.image_name}}"
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: create image from repository
      run: docker buildx build --platform linux/amd64 --cache-to type=gha --cache-from type=gha -t ${{ needs.setup.outputs.image_name }}
    - name: push image to GitHub Container Registry
      run: docker push ${{ needs.setup.outputs.image_name }}
